name: task_ecomerce
description: "E-Commerce Product Listing Application - MVC Architecture with Provider"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
